name: Weekly Timetable Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run timetable script
      env:
        SENDER: ${{ secrets.SENDER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        RECEIVER: ${{ secrets.RECEIVER }}
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        INTAKE_CODE: ${{ secrets.INTAKE_CODE }}
        REMOVE_LIST: ${{ secrets.REMOVE_LIST }}
      run: python timetable_converter.py
